language: node_js

# Use faster Docker architecture on Travis.
sudo: false

install: "npm update -g npm; npm install"
node_js:
  - iojs
  - "0.12"
  - "0.11"
  - "0.10"

repo_token: LuzWkYMVIUFsohBvk3z70OCP4zoI5q2Pz

script: "npm test && npm run coveralls && gulp test"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3da425911e19c51b9c99
    on_success: change
    on_failure: always
    on_start:   never

after_script:
  - npm run coveralls

